services:
  library_admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: library_admin
    container_name: library_admin
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - library_db
    networks:
      - library_network
    restart: always
    volumes:
      - .:/library_admin/
      - ./.env:/library_admin/.env

  # db
  library_db:
    image: postgres
    container_name: library_db
    volumes:
      - library_admin_data:/var/lib/postgresqal/data
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - library_network

  # broker
  broker:
    image: rabbitmq:3-management
    container_name: library_broker
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - library_network

networks:
  library_network:

volumes:
  library_admin_data: