# Generated by Django 4.2.16 on 2024-09-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('meta', models.JSONField(default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('BORROWED', 'BORROWED'), ('DELETED', 'DELETED'), ('AVAILABLE', 'AVAILABLE')], default='AVAILABLE')),
                ('available_date', models.DateTimeField(blank=True, help_text='date the book would be available to be borrowed again', null=True)),
                ('added_by', models.IntegerField(blank=True, help_text='id of the admin-user who added the book to the library', null=True)),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'db_table': 'book',
            },
        ),
    ]
